export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;

export type UserStatus = (typeof USER_STATUS)[keyof typeof USER_STATUS];

export const ENTITY_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
} as const;

export const PERMISSION_CODES = {
  BUSINESS_READ: 'BUSINESS_READ',
  BUSINESS_UPDATE: 'BUSINESS_UPDATE',
  LOCATION_READ: 'LOCATION_READ',
  LOCATION_CREATE: 'LOCATION_CREATE',
  LOCATION_UPDATE: 'LOCATION_UPDATE',
  LOCATION_DELETE: 'LOCATION_DELETE',
  STAFF_READ: 'STAFF_READ',
  STAFF_CREATE: 'STAFF_CREATE',
  STAFF_UPDATE: 'STAFF_UPDATE',
  STAFF_ACTIVATE: 'STAFF_ACTIVATE',
  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_ASSIGN_PERMISSIONS: 'ROLE_ASSIGN_PERMISSIONS',
  USER_ASSIGN_ROLE: 'USER_ASSIGN_ROLE',
  PATIENT_READ: 'PATIENT_READ',
  DOCTOR_READ: 'DOCTOR_READ',
  DOCTOR_CREATE: 'DOCTOR_CREATE',
  DOCTOR_UPDATE: 'DOCTOR_UPDATE',
  DOCTOR_ACTIVATE: 'DOCTOR_ACTIVATE',
  APPOINTMENT_READ: 'APPOINTMENT_READ',
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
  INVENTORY_READ: 'INVENTORY_READ',
  INVENTORY_CREATE: 'INVENTORY_CREATE',
  INVENTORY_UPDATE: 'INVENTORY_UPDATE',
} as const;

export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const ALL_PERMISSION_CODES = Object.values(PERMISSION_CODES);

export const SYSTEM_CREATED_USER_PASSWORD = 'Test@1234';

export const ROLE_CODES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_OWNER: 'TENANT_OWNER',
  DOCTOR: 'DOCTOR',
} as const;

export const DOCTOR_PERMISSION_CODES = [
  PERMISSION_CODES.PATIENT_READ,
  PERMISSION_CODES.DOCTOR_READ,
  PERMISSION_CODES.DOCTOR_UPDATE,
  PERMISSION_CODES.APPOINTMENT_READ,
  PERMISSION_CODES.APPOINTMENT_CREATE,
  PERMISSION_CODES.APPOINTMENT_UPDATE,
] as const;

export const APPOINTMENT_TYPES = [
  'Consultation',
  'Follow-up',
  'Check-up',
  'Procedure',
] as const;

export const DOCUMENT_KINDS = ['Consent', 'X-ray', 'Photo'] as const;

export const APPOINTMENT_STATUSES = [
  'Confirmed',
  'In progress',
  'Completed',
  'Cancelled',
  'Expired',
] as const;

export const INVENTORY_CATEGORIES = ['PPE', 'Fluids', 'Devices', 'Pharmacy', 'Consumables', 'Other'] as const;
export const INVENTORY_UNITS = ['boxes', 'packs', 'pcs', 'bottles', 'vials'] as const;

export const DEFAULT_CLINIC_HOURS = {
  openTime: '09:00',
  closeTime: '21:00',
} as const;

export interface ApiError {
  code: string;
  message: string;
}

export interface PaginatedData<T> {
  items: T[];
  page: number;
  pageSize: number;
  total: number;
}

export interface Address {
  line1?: string;
  line2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
}

export const ERROR_CODES = {
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  BUSINESS_TYPE_NOT_FOUND: 'BUSINESS_TYPE_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  TENANT_INACTIVE: 'TENANT_INACTIVE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_STATUS: 'APPOINTMENT_STATUS',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
} as const;
